name: Generate release for Link Nacional File Browser Plugin

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

env:
  PLUGIN_NAME: lknwp-filebrowser
  PHP_VERSION: "7.4"
  PLUGIN_VERSION: '1.0.1'

jobs:
  release-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    # Run composer install and generate vendor
    - name: Run composer install
      uses: php-actions/composer@v6
      with:
        php_version: ${{ env.PHP_VERSION }}
        working_dir: "."
        args: --ignore-platform-reqs
        command: install
        dev: no

    # Add plugin files to a root directory
    - name: Prepare plugin folder
      run: |
        mkdir -p dist
        mkdir -p build/${{ env.PLUGIN_NAME }}
        mv ./admin ./includes ./public ./languages *.php LICENSE.txt composer.json composer.lock ./build/${{ env.PLUGIN_NAME }}
        find ./build -type f -exec chmod 0644 {} +
        find ./build -type d -exec chmod 0755 {} +
    
    # Move vendor directory separately (can be slow)
    - name: Move vendor directory
      run: |
        cp -r ./vendor ./build/${{ env.PLUGIN_NAME }}/vendor

    # Compact plugin as .zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: '.'
        directory: 'build'
        filename: '${{ env.PLUGIN_NAME }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Move .zip to custom location
      run: |
        mv ./build/${{ env.PLUGIN_NAME }}.zip ./dist/

    # Update version tag
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: '${{ env.PLUGIN_VERSION }}'

    # Generate new release
    - name: Generate new Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/${{ env.PLUGIN_NAME }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: "main"
        draft: true
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        